# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  name "courier"
  desc "The official Courier CLI for managing notifications from the command line."
  homepage "https://courier.com"
  version "3.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"
  manpage "man/man1/courier.1.gz"
  bash_completion "completions/courier.bash"
  zsh_completion "completions/courier.zsh"
  fish_completion "completions/courier.fish"

  on_macos do
    on_intel do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_macos_amd64.zip"
      sha256 "ab7512040600f9d1fa922a6a2e6cd0f7c9b30fcf427468e2b87f050c86f0f45b"
    end
    on_arm do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_macos_arm64.zip"
      sha256 "d4ba0b1cc80500c48776dacd1da59c0c8b5cfbe25b6040a9787f499cdbf26aba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
      sha256 "21682511c5787df6c506496606a03cf825deba65e7c36d7dcd02c588a3c4c489"
    end
    on_arm do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
      sha256 "757464b8dbb5cfdb77aec8bfd2f93d08f0415cd1bb344953ceb1b5982f39d899"
    end
  end

  # No zap stanza required
end
