# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  name "courier"
  desc "The official Courier CLI for managing notifications from the command line."
  homepage "https://courier.com"
  version "3.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"
  manpage "man/man1/courier.1.gz"
  bash_completion "completions/courier.bash"
  zsh_completion "completions/courier.zsh"
  fish_completion "completions/courier.fish"

  on_macos do
    on_intel do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_macos_amd64.zip"
      sha256 "2f41e0651e9a2107f5dd66b1d2c23d68eaf17e91a9d33a661d35e7e924e12267"
    end
    on_arm do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_macos_arm64.zip"
      sha256 "9f8d4c3663c331a394b6bbc6a2050eb7c306e65ac099b3676dceabdaaeee4f73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
      sha256 "22d1f7dc2f45de79d4d26ba84b5a01cc3e10cfbe1396b0d14f109559648bb677"
    end
    on_arm do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
      sha256 "115ffdc404d22ee5fe55f83c83bfbe92c0eefdba54237f0e89b6a189c57ce76f"
    end
  end

  # No zap stanza required
end
