# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  name "courier"
  desc "The official Courier CLI for managing notifications from the command line."
  homepage "https://courier.com"
  version "3.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"
  manpage "man/man1/courier.1.gz"
  bash_completion "completions/courier.bash"
  zsh_completion "completions/courier.zsh"
  fish_completion "completions/courier.fish"

  on_macos do
    on_intel do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_macos_amd64.zip"
      sha256 "c3bb873e6a12cccf8e2d5938137f9031df551ae1205b592b4abeb0a502d6a2e1"
    end
    on_arm do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_macos_arm64.zip"
      sha256 "2db97ca7888fb136681fef948e3a0c862f469b4e56854a75316ccf5178c4fbc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_linux_amd64.tar.gz"
      sha256 "4053356ab08302f29f7790c4739ce064625b9b6aab90cab0aca276bc3d43a2ad"
    end
    on_arm do
      url "https://github.com/trycourier/courier-cli/releases/download/v#{version}/courier_#{version}_linux_arm64.tar.gz"
      sha256 "f46efb96c8c3d5ac2b77afbfa9caaed55396db11e79347d13e3f79e2c1fa51bd"
    end
  end

  # No zap stanza required
end
